/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_spaces_calculator_calculations_Matrix */

#ifndef _Included_by_spaces_calculator_calculations_Matrix
#define _Included_by_spaces_calculator_calculations_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_spaces_calculator_calculations_Matrix_init__
  (JNIEnv *, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_by_spaces_calculator_calculations_Matrix_init__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_by_spaces_calculator_calculations_Matrix_init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    init
 * Signature: ([[D)V
 */
JNIEXPORT void JNICALL Java_by_spaces_calculator_calculations_Matrix_init___3_3D
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    getRows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_spaces_calculator_calculations_Matrix_getRows
  (JNIEnv *, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    getCols
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_by_spaces_calculator_calculations_Matrix_getCols
  (JNIEnv *, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    getData
 * Signature: ()[[D
 */
JNIEXPORT jobjectArray JNICALL Java_by_spaces_calculator_calculations_Matrix_getData
  (JNIEnv *, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    add
 * Signature: (Lby/spaces/calculator/calculations/Matrix;)Lby/spaces/calculator/calculations/Matrix;
 */
JNIEXPORT jobject JNICALL Java_by_spaces_calculator_calculations_Matrix_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    subtract
 * Signature: (Lby/spaces/calculator/calculations/Matrix;)Lby/spaces/calculator/calculations/Matrix;
 */
JNIEXPORT jobject JNICALL Java_by_spaces_calculator_calculations_Matrix_subtract
  (JNIEnv *, jobject, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    multiply
 * Signature: (D)Lby/spaces/calculator/calculations/Matrix;
 */
JNIEXPORT jobject JNICALL Java_by_spaces_calculator_calculations_Matrix_multiply__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    multiply
 * Signature: (Lby/spaces/calculator/calculations/Matrix;)Lby/spaces/calculator/calculations/Matrix;
 */
JNIEXPORT jobject JNICALL Java_by_spaces_calculator_calculations_Matrix_multiply__Lby_spaces_calculator_calculations_Matrix_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    findDeterminant
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_by_spaces_calculator_calculations_Matrix_findDeterminant
  (JNIEnv *, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_spaces_calculator_calculations_Matrix_print
  (JNIEnv *, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    inverseMatrix
 * Signature: ()Lby/spaces/calculator/calculations/Matrix;
 */
JNIEXPORT jobject JNICALL Java_by_spaces_calculator_calculations_Matrix_inverseMatrix
  (JNIEnv *, jobject);

/*
 * Class:     by_spaces_calculator_calculations_Matrix
 * Method:    transpose
 * Signature: ()Lby/spaces/calculator/calculations/Matrix;
 */
JNIEXPORT jobject JNICALL Java_by_spaces_calculator_calculations_Matrix_transpose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
