/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_spaces_calculator_calculations_Converter */

#ifndef _Included_by_spaces_calculator_calculations_Converter
#define _Included_by_spaces_calculator_calculations_Converter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_spaces_calculator_calculations_Converter
 * Method:    convertBase
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_by_spaces_calculator_calculations_Converter_convertBase
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     by_spaces_calculator_calculations_Converter
 * Method:    validateNumber
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_by_spaces_calculator_calculations_Converter_validateNumber
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
